### ISSUE TITLE
Bad Indentation of a Mapping Entry

### ISSUE THREAD

**Issue by Mtechnik** [0x2E/Material-T#31]
This is what im getting once I get to step 3 
`3. Create About Page

hexo new page about`

`PS E:\Site\blog\themes> hexo new page about
FATAL bad indentation of a mapping entry at line 86, column 3:
      yearly : true
      ^
YAMLException: bad indentation of a mapping entry at line 86, column 3:
      yearly : true 
      ^
    at generateError (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1092:7)
    at composeNode (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1344:12)
    at readDocument (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1504:3)
    at loadDocuments (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1560:5)
    at Object.load (E:\Site\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1581:19)
    at Hexo.yamlHelper (E:\Site\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (E:\Site\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\Site\blog\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (E:\Site\blog\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (E:\Site\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Site\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\Site\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Site\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Site\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (E:\Site\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (E:\Site\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\Site\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Site\blog\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (timers.js:637:19)`

and its confusing because Im doing exactly what you say do in your README.md

**Comment by 0x2E** [comment]
Hi @Mtechnik 
>hexo new page about FATAL bad indentation of a mapping entry at line 86, column 3: yearly : true ^ YAMLException: bad indentation of a mapping entry at line 86, column 3: yearly : true ^

This is due to a yaml format error, please check the location.
1. In yaml, there should be a space between the colon and the value of the property.

- `yearly: true` :heavy_check_mark:
- `yearlu:true` :x:
 
2. Attributes should be correctly indented

**Comment by Mtechnik** [comment]
ok ill try that
